### ISSUE TITLE
How to access underlying server

### ISSUE THREAD

**Issue by Pezmc** [fastify/restartable#45]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Previously without this module we would boot fastify as follows:

```
const server = await initServer()
server.listen({ port: server.config.port, host: server.config.host }
```

With restartable, this looks like:

```
const server = await restartable(initServer, { logger: true })
// How to read server.config.port?
```

How does one access the underlying server object to read things like .config? The wrapper seems to return an object `{ then: undefined }` which has the apps prototype copied over.

https://github.com/fastify/restartable/blob/0b02b0d46c44ba6f192e419bc2e2ecb93a086bfc/index.js#L9

Currently I see:

```
TypeError: Cannot read properties of undefined (reading 'port')
    at app.js:55:45
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Pezmc** [comment]
I got to the bottom of my issue, and I believe it's a bug in this module, proposed fix in #46

**Comment by ivan-tymoshenko** [comment]
Here is an example: https://github.com/fastify/restartable#usage

**Comment by Fdawgs** [comment]
@Pezmc Did Ivan's response solve your issue?
